### PR TITLE
dev: improve python-run-tests execution

### LINKED ISSUE #755: reana-dev python-unit-tests: allow running selected tests only
Improve the command to create desired Python 3.8 virtual environments, to allow excluding Python components, and to exit gracefully on errors.

Allow execution of selected pytests only.

The goal is to have a fully functioning command:

```console
$ reana-dev python-unit-tests -c CLIENT -c CLUSTER -k
```

which currently fails.

### PR DESCRIPTION
**Pull request by tiborsimko**
Improves the `python-run-tests` command to create Python-3.8 based virtual environments to use the same version as container images.

Updates `pip` before installing each component in order to speed up the dependency resolution for certain cluster components.

Allows execution of selected pytests only by passing over `PYTEST_ADDOPTS` environment variable.

Switches to using `run-tests.sh` to execute pytests in individual components which takes care of the DB setup at the source.

Allows excluding certain Python components such as `-c CLUSTER --exclude-components r-j-controller` on macOS.

Example:

```
$ PYTEST_ADDOPTS=tests/test_version.py reana-dev python-unit-tests -c ALL -k
```

Closes #755.

### CODE REVIEW

**Comment by tiborsimko** [comment]
How to test:

```console
$ reana-dev git-checkout-pr --fetch \
    -b reana 756 \
    -b pytest-reana 114 \
    -b reana-client  684 \
    -b reana-commons  419 \
    -b reana-db 208  \
    -b reana-demo-cms-reco 30 \
    -b reana-job-controller 441 \
    -b reana-message-broker 57 \
    -b reana-server 639 \
    -b reana-workflow-controller 537 \
    -b reana-workflow-engine-cwl 251 \
    -b reana-workflow-engine-serial 188 \
    -b reana-workflow-engine-snakemake 69 \
    -b reana-workflow-engine-yadage 246

$ PYTESTARG=tests/test_version.py reana-dev python-unit-tests -c ALL -k
```

File: run-tests.sh [hunk 1]
```diff
@@ -37,7 +37,11 @@ check_sphinx () {
 }
 
 check_pytest () {
-    python setup.py test
+    if [ -n "${PYTESTARG-}" ]; then
+        pytest "$PYTESTARG"
+    else
+        python setup.py test
+    fi
```
Comment (mdonadoni) [inline run-tests.sh:44]: I think that the changes to this file should not be needed

File: CHANGES.rst [hunk 2]
```diff
@@ -1,6 +1,14 @@
 Changes
 =======
 
+Version 0.9.2 (UNRELEASED)
+--------------------------
+
+- Developers:
+    - Changes `python-run-tests` command to allow execution of selected pytests only by passing over `PYTESTARG` environment variable.
```
Comment (mdonadoni) [inline CHANGES.rst:8]:
```suggestion
    - Changes `python-run-tests` command to allow execution of selected pytests only by passing over `PYTEST_ADDOPTS` environment variable.
```

**Review by mdonadoni — APPROVED** [review]
